version: '3.6'
services:
  cli:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - sftp-server
    tty: true
    command: "sleep 0"
    container_name: 'cache-cli'
    volumes:
      - go-pkg-cache:/go
      - .:/app
    environment:
      NEETO_CI_TOOLBOX_METRICS_ENABLED: "true"
  sftp-server:
    container_name: sftp-server
    ports:
      - "2222:22"
    build:
      context: .
      dockerfile: Dockerfile.sftp_server
volumes:
  go-pkg-cache:
    driver: local